import java.util.PriorityQueue;
import java.util.Scanner;
public class Main {
	static PriorityQueue<Student> queue=new PriorityQueue<Student>(new StudentCompare());
	static int token=0;// for unique token value 
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		int sampleInput;					//
		System.out.println("enter the sample input:");
		sampleInput=sc.nextInt();
		for(int i=0;i<sampleInput;i++) {
			int y;
			System.out.println("enter the choice 0 to Enter the student data and 1 for Serving the student");
			try {
			y=sc.nextInt();
			}
			catch (Exception e) {
				System.out.println("enter the integer value only");
				y=sc.nextInt();
			}
			switch(y) {
				case 0:
					queue=Enter();
					break;
				case 1:
					queue=served();
					if(queue!=null)
					System.out.println("SERVED");
					break;
				default :
					System.out.println("select the right choice");
			}
		}
			if(queue!=null) {
			System.out.println("Unserved people");
			while (!queue.isEmpty()) { 
				
				System.out.println(queue.poll().getData());
			}
			}
			else {
				System.out.println("Empty");
			}
		sc.close();
		
		
	}
	public static PriorityQueue<Student> Enter() {	// getting Student details from user 
		String name;
		float cgpa;
		System.out.println("enter the details of student");
		Scanner sc =new Scanner(System.in);
		try {
		System.out.println("enter the name");
		name=sc.next();
		}
		catch(Exception e) {
			System.out.println("enter the name as String");
			name=sc.next();
		}
		try {
			System.out.println("enter the cgpa");
			cgpa=sc.nextFloat();
			}
			catch(Exception e) {
				System.out.println("enter the cgpa in floating value ");
				cgpa=sc.nextFloat();
			}
		
		queue.add(new Student(name,cgpa,token++));// token values are auto incrementing and unique and generated by system
		return queue;
	}
	public static PriorityQueue<Student> served() {
		
		if(queue.isEmpty()) {
			
			return null;
		}
		else{
		queue.poll(); //remove the most prior element from queue
		return queue;
		}
	}
	
	
}
